######################################################################
# Automatically generated by qmake (3.0) Mon Dec 7 09:18:14 2015
######################################################################

TEMPLATE = app
TARGET = game
INCLUDEPATH += .

# Input
HEADERS += graphicsScene.h layout.h monster.h room.h
SOURCES += graphicsScene.cpp main.cpp monster.cpp room.cpp
RESOURCES += monsters.qrc
